[DPE-4642] Multiple databases
canonical/pgbouncer-k8s-operator pull request #324
Opened 2024-06-26 09:24 UTC by dragomirp

## Issue

## Solution

2024-06-27 19:57 UTC, dragomirp commented on src/charm.py
> +        self._cores = max(min(os.cpu_count(), 4), 2)
Not strictly necessary, but limiting instances. We don't have to stop on upgrade since old pod goes away.

2024-06-27 19:59 UTC, dragomirp commented on src/charm.py
> +
Waiting to the end to set `current_port` to make sure that restarts will happen if the event got deferred.

2024-06-27 19:59 UTC, dragomirp commented on .github/workflows/ci.yaml
> +          - agent: 3.1.8  # renovate: juju-agent-pin-minor
Missed pin

2024-06-27 20:00 UTC, dragomirp commented on src/charm.py
> +                pgb_container.send_signal(SIGHUP, service["name"])
Reload, unless requested or the service is not active.

2024-06-27 21:38 UTC, marceloneppel requested changes

2024-06-27 21:47 UTC, marceloneppel approved these changes

2024-06-28 10:19 UTC, taurus-forever approved these changes
Tnx!

2024-06-28 10:20 UTC, merged