Tweak renovate
canonical/pgbouncer-k8s-operator pull request #58
Opened 2023-03-21 15:05 UTC by dragomirp

## Proposal
* Don't ignore tests, so that tests charms are also updated

## Context

## Release Notes

## Testing

2023-03-21 15:10 UTC, dragomirp commented on renovate.json
> +  ],
These are the defaults without `"**/tests/**",`. We should be OK with removing all of them if we don't want them cluttering the config

2023-03-21 16:48 UTC, taurus-forever requested changes

2023-03-21 21:28 UTC, taurus-forever approved these changes

2023-03-22 09:31 UTC, marceloneppel approved these changes

2023-03-22 10:04 UTC, merged