add release to charmhub
canonical/pgbouncer-k8s-operator pull request #8
Opened 2022-07-13 14:16 UTC by paulomach

## Issue

Auto publish to charmhub. Temporarily using image from [this dockerhub registry](https://hub.docker.com/r/dataplatformoci/pgbouncer)

## Release Notes

- `.github/workflows/ci.yaml` - removed OCI build steps
- `.github/workflows/release.yaml` - release workflow
- `CONTRIBUTING.md` - update instructions
- `metadata.yaml` - updated upstream source

2022-07-15 19:47 UTC, marcoppenheimer approved these changes

2022-07-18 06:02 UTC, delgod approved these changes

2022-07-18 08:34 UTC, WRFitch requested changes
LGTM, thanks again for the changes! 

Unfortunately I have to block this PR for the same reasons as the other one in `pgbouncer-operator` - I don't feel this charm is ready for release, so I can't approve automated releases. The two tasks left to complete are integration testing and the db relations.

2022-08-03 22:06 UTC, WRFitch approved these changes
LGTM :)

2022-08-05 07:07 UTC, MiaAltieri approved these changes
LGTM one comment though :)

2022-08-05 07:07 UTC, MiaAltieri commented on .github/workflows/ci.yaml
>          # set a predictable model name so it can be consumed by charm-logdump-action
might want to also remove this comment

2022-08-10 07:40 UTC, MiaAltieri approved these changes
nice 🤩

2022-08-10 13:41 UTC, marceloneppel approved these changes
LGTM!

2022-08-10 14:19 UTC, merged